ubuntu_amd64_task:
  container:
    image: ubuntu:focal
  install_script:
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive apt-get -y dist-upgrade
    - DEBIAN_FRONTEND=noninteractive apt-get -y install cmake perl
  build_script:
    - cmake .
    - make -j$(getconf _NPROCESSORS_ONLN)
  test_script:
    ctest --output-on-failure

ubuntu_arm64_task:
  arm_container:
    image: ubuntu:focal
  install_script:
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive apt-get -y dist-upgrade
    - DEBIAN_FRONTEND=noninteractive apt-get -y install cmake perl
  build_script:
    - cmake .
    - make -j$(getconf _NPROCESSORS_ONLN)
  test_script:
    ctest --output-on-failure

freebsd_13_task:
  freebsd_instance:
    image: freebsd-13-0-release-amd64
  install_script:
    pkg install -y cmake perl5
  build_script:
    - NPROC=$(getconf _NPROCESSORS_ONLN)
    - cmake .
    - make -j${NPROC}
  test_script:
      # run tests as user "cirrus" instead of root
    - pw useradd cirrus -m
    - chown -R cirrus:cirrus .
    - sudo -u cirrus ctest --output-on-failure

macos_x_task:
  macos_instance:
    image: big-sur-xcode
  install_script:
    - brew update
    - brew install cmake
  build_script:
    - NPROC=$(getconf _NPROCESSORS_ONLN)
    - cmake .
    - make -j${NPROC}
  test_script:
    ctest --output-on-failure
